# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TimeSeries": "00_core.ipynb",
         "TimeseriesModel": "00_core.ipynb",
         "NaiveForecast": "00_core.ipynb",
         "TrendForecast": "00_core.ipynb",
         "ForecastingTask": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://KkeipertCelver.github.io/celverapi/"

git_url = "https://github.com/KkeipertCelver/celverapi/tree/master/"

def custom_doc_links(name): return None
